tap "homebrew/cask"
tap "heroku/brew"
tap "planetscale/tap"
tap "cloudflare/cloudflare"
tap "superfly/tap"
tap "vectordotdev/brew"

# Terminal
brew "tmux"
cask  "iterm2", args: { appdir: "/Applications"}
brew "zsh"
brew "reattach-to-user-namespace"
brew "neovim"
brew "wget"
brew "vector"

# Databases
brew "postgres"
brew "mysql"

# Languages
brew "node"
brew "deno"
brew "nodenv"
brew "yarn"
brew "rbenv"
brew "watchman"
brew "pyenv-virtualenv"

# ClI
brew "mitmproxy"
brew "terraform"
brew "heroku"
brew "flyctl"
brew "gh"
brew "pscale"
brew "awscli"
brew "aws-iam-authenticator"
brew "gpg2"
brew "cloudflared"

# Kube
cask "lens", args: { appdir: "/Applications" }

# Devtools
cask "macvim", args: { appdir: "/Applications"}
cask "docker", args: { appdir: "/Applications"}
cask "graphiql", args: { appdir: "/Applications"}
cask "raycast", args: { appdir: "/Applications" }
cask "linear-linear", args: { appdir: "/Applications" }


# Knowledge/Communications
cask  "slack", args: { appdir: "/Applications"}
cask  "notion", args: { appdir: "/Applications"}
cask  "zoom", args: { appdir: "/Applications"}
cask  "tableplus", args: { appdir: "/Applications"}
cask  "paw", args: { appdir: "/Applications"}
cask  "loom", args: { appdir: "/Applications"}
cask  "obsidian", args: { appdir: "/Applications"}
cask  "cron", args: { appdir: "/Applications"}

# Misc
cask "spotify", args: { appdir: "/Applications"}
cask "google-chrome", args: { appdir: "/Applications"}
# cask "istat-menus"
cask "visual-studio-code", args: { appdir: "/Applications"}
cask "1password", args: { appdir: "/Applications"}


# Mac app store
mas 'Xcode', id: 497_799_835
mas 'Paste', id: 967_805_235
mas 'SimpleNote', id: 692_867_256
