tap "homebrew/cask"

# Terminal
brew "tmux"
cask  "iterm2", args: { appdir: "/Applications"}
brew "zsh"

# Databases
brew "postgres"

# Languages
brew "node"
brew "nodenv"
brew "rbenv"
brew "watchman"

# ClI
brew "mitmproxy"
brew "terraform"
brew "awscli"
brew "pyenv-virtualenv"
brew "gpg2"


# Devtools
cask  "macvim", args: { appdir: "/Applications"}
cask  "virtualbox", args: { appdir: "/Applications"}
cask  "graphiql", args: { appdir: "/Applications"}

# Workflow
cask  "skitch", args: { appdir: "/Applications"}

# Knowledge/Communications
cask  "slack", args: { appdir: "/Applications"}
cask  "notion", args: { appdir: "/Applications"}

# Misc
cask "spotify", args: { appdir: "/Applications"}
cask "google-chrome", args: { appdir: "/Applications"}

